---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1qpy5ren2fs50txk8fjlqgajchq975zayg7265vj5xzj6sg3ye9rslq3a6y
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1qpy5ren2fs50txk8fjlqgajchq975zayg7265vj5xzj6sg3ye9rslq3a6y
