---
kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: dev-cluster
image: rancher/k3s:v1.23.3-k3s1
servers: 3
agents: 3
# ports:
# - port: 80:80
#   nodeFilters:
#   - loadbalancer
options:
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
  k3d:
    timeout: "60s"
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
